---
title: "NosAutoanalizamos"
author: "Josep Peiro Ramos"
date: "8/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Especificamos las librerías necesarias en esta lista

packages = c("tidyverse","knitr", "readr", "forcats", "stringr", "dplyr", "ggplot2", "lubridate", "assertive", "GGally", "purrr")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
  }
  library(x, character.only = TRUE)
})

#verify they are loaded
search()
```

```{r}
datos = read_tsv("./data/NosAutoanalizamos2020 - Hoja1.tsv", skip=27) %>% select(-1)
glimpse(datos)
#El unico cambio sustancial que he hecho en este trabajo ha sido cambiar el numero de lineas que salta de 25 a 27, porque por razones que no podemos controlar, este archivo requeria de ese cambio
```

```{r}
datos = datos %>% filter(Id != "martsobm")
```

```{r}
datos=datos %>% rename(Fecha_Nac=1, Size_Hand=Wr.Hnd, Laterality=NW.Hnd, Study_Hours = HSt, Work_Hours=Hwork)
datos
```

```{r, warning=F}
datos=datos %>%mutate(ALG=str_replace(ALG, "NC", "3.0"), 
                      ANM =str_replace(ANM, "NC", "3.0"), 
                      FP=str_replace(FP, "NC", "3.0"), 
                      DCS = str_replace(DCS, "NC", "3.0"), 
                      MD=str_replace(MD, "NC", "3.0")) %>%
               mutate(ALG=as.numeric(str_replace(ALG, ",", ".")),
                      ANM=as.numeric(str_replace(ANM, ",", ".")),
                      FP=as.numeric(str_replace(FP, ",", ".")),
                      DCS=as.numeric(str_replace(ALG, ",", ".")),
                      MD=as.numeric(str_replace(MD, ",", "."))) %>% 
               mutate(ALG=ifelse(ALG>10, ALG/10, ALG),
                      ANM=ifelse(ANM>10, ANM/10, ANM),
                      FP=ifelse(FP>10, FP/10, FP),
                      DCS=ifelse(DCS>10, DCS/10, DCS),
                      MD=ifelse(MD>10, MD/10, MD))
```

```{r}
datos=datos %>% mutate(Fecha_Nac=dmy(str_replace(Fecha_Nac, "/", "-"))) %>% mutate_if(is.character, as.factor) %>% mutate(Comentarios=as.character(Comentarios))
```

```{r}
estadisticos = function(x){
  minimo = round(min(x, na.rm=T),2)
  percentil_25 = round(quantile(x, 0.25, na.rm=T),2)
  mediana = round(median(x, na.rm=T),2)
  media = round(mean(x, na.rm=T),2)
  desviacion_tipica = round(sd(x, na.rm=T),2)
  percentil_75 = round(quantile(x, 0.75, na.rm=T),2)
  maximo = round(max(x, na.rm=T),2)
  vector = c(minimo, percentil_25, mediana, media, desviacion_tipica, percentil_75, maximo)
  return (vector)
}
```

```{r}
algebra = estadisticos(datos$ALG)
analisis = estadisticos(datos$ANM)
programacion = estadisticos(datos$FP)
sociedad = estadisticos(datos$DCS)
discreta = estadisticos(datos$MD)
```

```{r}
matriz_est =rbind(algebra, analisis, programacion, sociedad, discreta)
matriz_est
tabla_estadisticos = cbind(rownames(matriz_est), as.data.frame(matriz_est))
colnames(tabla_estadisticos)=c("asigantura","minimo", "percentil_25", "mediana", "media", "desviacion_tipica", "percentil_75", "maximo")
rownames(tabla_estadisticos)=NULL
tabla_estadisticos
```

```{r, warning=FALSE}
ggpairs(datos[,13:17])
```

```{r}
cov(datos[,13:17],method = 'pearson', use = "na.or.complete")
cor(datos[,13:17],method = 'pearson', use = "na.or.complete")
```
Los pares que mas correlacion tienen son Analisis Matematico con Matetamitca Discreta 

```{r}
datos[,13:17] %>% gather("asignatura", "nota", 1:5) %>% ggplot(aes(asignatura, nota))+geom_boxplot()
```

```{r}
datos=datos %>% mutate(Sex=fct_collapse(Sex, "F"=c("F", "Femenino"), "M"=c("M", "Masculino")))

datos %>% select(Sex, 13:17)%>% gather("asignatura", "nota", 2:6) %>% ggplot(aes(asignatura, nota, color=Sex))+geom_boxplot()
```

```{r}

```

